### ISSUE TITLE
TypeError: Cannot read property 'CallNumber' of undefined

### ISSUE THREAD

**Issue by vivekpandey0460** [Rohfosho/CordovaCallNumberPlugin#16]
Its giving me TypeError: Cannot read property 'CallNumber' of undefined error.

Please help on this.

**Comment by nishilshah17** [comment]
When is this error occurring?

**Comment by vivekpandey0460** [comment]
When i tried to call the dial function from my controller

**Comment by CrystalVisions** [comment]
I got this same error when trying to run my app after installing the plugin using 
           `npm install call-number`
I then installed it using 
            `cordova plugin add https://github.com/Rohfosho/CordovaCallNumberPlugin.git`
and it worked fine.

**Comment by nishilshah17** [comment]
Ah ok, I had forgotten to publish the updated npm package. Sorry about that. Fixed now.

**Comment by pankaja92** [comment]
I'm having the same error. When I run the function I'm getting this error. Even I added the script file to the page. Still getting this error. What is the fix for this ?

TypeError: Cannot read property 'CallNumber' of undefined
